name: flowkeeper
base: core24
version: "1.0.2"
license: GPL-3.0-only

summary: Flowkeeper is a free Pomodoro Technique desktop timer for power users.
description: |
    Flowkeeper is a Pomodoro backlog and timer with a "classic" desktop-first UI paradigm.
    With its keyboard shortcuts and advanced settings, it is optimized for power users.
    It stays as close as possible to the Pomodoro Technique definition and format from
    the original book by Francesco Cirillo.

grade: devel
confinement: classic

platforms:
    amd64:
    arm64:

apps:
    flowkeeper:
        command: usr/bin/flowkeeper
        environment:
            LD_LIBRARY_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_ON:$SNAP/usr/lib:$LD_LIBRARY_PATH
        common-id: org.flowkeeper.Flowkeeper
        desktop: usr/share/applications/org.flowkeeper.Flowkeeper.desktop
        plugs:
          - desktop
          - desktop-legacy
          - opengl
          - wayland
          - x11
          - audio-playback
          - unity7
          - network
          - network-bind


parts:
    flowkeeper:
        plugin: dump
        source:
            - on amd64: https://github.com/flowkeeper-org/fk-desktop/releases/download/v1.0.2/flowkeeper-1.0.2-ubuntu-22.04-nuitka-package.deb
            - on arm64: https://github.com/flowkeeper-org/fk-desktop/releases/download/v1.0.2/flowkeeper-1.0.2-ubuntu-22.04-arm-nuitka-package.deb
        source-type: deb
        stage-packages:
            - libxcb-cursor0
            - libgl1
            - libpulse0
            # dependencies for Video Acceleration
            - libva2
            - libva-drm2
            - libva-x11-2
            # missing dependencies as per linter
            - libegl1 # libEGL.so.1
            - libqt6opengl6t64 # libQt6EglFsKmsGbmSupport.so.6
            - libxrandr2 # libXrandr.so.2
            - libatk1.0-0t64 # libatk-1.0.so.0
            - libatomic1 # libatomic.so.1
            - libcairo-gobject2 # libcairo-gobject.so.2
            - libcairo2 # libcairo.so.2
            - libcups2t64 # libcups.so.2
            - libfontconfig1 # libfontconfig.so.1
            - libgtk-3-0t64 # libgdk-3.so.0
            - libgdk-pixbuf-2.0-0 # libgdk_pixbuf-2.0.so.0
            - libgtk-3-0t64 # libgtk-3.so.0
            - libpango-1.0-0 # libpango-1.0.so.0
            - libpangocairo-1.0-0 # libpangocairo-1.0.so.0
            - libwayland-client0 # libwayland-client.so.0
            - libwayland-cursor0 # libwayland-cursor.so.0
            - libwayland-egl1 # libwayland-egl.so.1

        override-prime: |
            craftctl default

            if [ -f "$CRAFT_PRIME/usr/share/applications/org.flowkeeper.Flowkeeper.desktop" ]; then
              sed -i 's|^Exec=.*|Exec=flowkeeper|' \
                "$CRAFT_PRIME/usr/share/applications/org.flowkeeper.Flowkeeper.desktop"

              sed -i 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/1024x1024/apps/org.flowkeeper.Flowkeeper.png|' \
                "$CRAFT_PRIME/usr/share/applications/org.flowkeeper.Flowkeeper.desktop"
            fi
