name: flowkeeper
base: core24
version: "1.0.2"
license: GPL-3.0-only

summary: Flowkeeper is a free Pomodoro Technique desktop timer for power users.
description: |
    Flowkeeper is a Pomodoro backlog and timer with a "classic" desktop-first UI paradigm.
    With its keyboard shortcuts and advanced settings, it is optimized for power users.
    It stays as close as possible to the Pomodoro Technique definition and format from
    the original book by Francesco Cirillo.

grade: devel
confinement: classic

platforms:
    amd64:
    arm64:

apps:
    flowkeeper:
        command: usr/bin/flowkeeper
        common-id: org.flowkeeper.Flowkeeper
        desktop: usr/share/applications/org.flowkeeper.Flowkeeper.desktop
        plugs:
          - desktop
          - desktop-legacy
          - opengl
          - wayland
          - x11
          - audio-playback
          - unity7
          - network
          - network-bind


parts:
    flowkeeper:
        plugin: dump
        source:
            - on amd64: https://github.com/flowkeeper-org/fk-desktop/releases/download/v1.0.2/flowkeeper-1.0.2-ubuntu-22.04-nuitka-package.deb
            - on arm64: https://github.com/flowkeeper-org/fk-desktop/releases/download/v1.0.2/flowkeeper-1.0.2-ubuntu-22.04-arm-nuitka-package.deb
        source-type: deb

        stage-packages:
            - libglib2.0-0
            - libxcb-cursor0
            - libxcb-keysyms1
            - libxcb-icccm4

        override-prime: |
            craftctl default

            if [ -f "$CRAFT_PRIME/usr/share/applications/org.flowkeeper.Flowkeeper.desktop" ]; then
              sed -i 's|^Exec=.*|Exec=flowkeeper|' \
                "$CRAFT_PRIME/usr/share/applications/org.flowkeeper.Flowkeeper.desktop"

              sed -i 's|^Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/1024x1024/apps/org.flowkeeper.Flowkeeper.png|' \
                "$CRAFT_PRIME/usr/share/applications/org.flowkeeper.Flowkeeper.desktop"
            fi
