name: Build subflow

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      compiler:
        required: true
        type: string
      tag:
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        shell: bash
        run: |
          export FK_VERSION=$(scripts/common/get-version.sh)
          echo "FK_VERSION=$FK_VERSION" >> $GITHUB_ENV

          scripts/linux/appimage/install-appimage.sh
          export BINARY_EXTENSION=""
          echo "BINARY_EXTENSION=" >> $GITHUB_ENV

          pip install -r requirements.txt

          if [[ "${{ inputs.compiler}}" == "nuitka" ]]; then
            pip install nuitka
          else
            pip install pyinstaller
          fi

      - name: Prepare sources
        shell: bash
        run: |
          scripts/common/generate-resources.sh
          rm -rf build dist
          mkdir -p build dist

      - name: Package builds (PyInstaller)
        if: ${{ inputs.compiler == 'pyinstaller' }}
        shell: bash
        run: |
          pyinstaller scripts/common/pyinstaller/portable.spec --distpath=build
          pyinstaller scripts/common/pyinstaller/normal.spec --distpath=build
          echo "Built PyInstaller for Linux"
          ls -al build/

      - name: Package builds (Nuitka)
        if: ${{ inputs.compiler == 'nuitka' }}
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: "2.6.8"
          script-name: src/fk/desktop/desktop.py
          mode: onefile
          enable-plugins: pyside6
          include-qt-plugins: multimedia
          product-name: Flowkeeper
          product-version: "${{ env.FK_VERSION }}"
          file-description: Flowkeeper is a Pomodoro Technique desktop timer for power users
          copyright: Copyright (c) 2023 Constantine Kulak <contact@flowkeeper.org>
          output-dir: 'build'
          output-file: 'Flowkeeper'
        env:
          PYTHONPATH: src

      - name: Create installers
        shell: bash
        run: |
          echo "Prepare dist directory"
          mkdir -p dist/standalone
          PREFIX="dist/flowkeeper-${FK_VERSION}-${{ inputs.os }}-${{ inputs.compiler }}"
          echo "Will create artifacts with $PREFIX prefix"

          if [[ "${{ inputs.compiler}}" == "nuitka" ]]; then
            mv build/Flowkeeper* $PREFIX-portable
            mv build/desktop.dist/* dist/standalone
            mv dist/standalone/Flowkeeper.bin dist/standalone/Flowkeeper
          else
            mv build/Flowkeeper $PREFIX-portable
            mv build/flowkeeper/* dist/standalone
          fi
          echo "Moved ${{ inputs.compiler }} binaries to dist/standalone"
          find dist/

          echo "Building Debian \"fat\" DEB package"
          scripts/linux/debian/package-deb.sh
          mv dist/flowkeeper.deb "$PREFIX-package.deb"

          echo "Building Debian \"lean\" DEB package"
          scripts/linux/debian/package-deb-min.sh
          mv dist/flowkeeper-min.deb "$PREFIX-min-package.deb"

          echo "Building AppImage package"
          scripts/linux/appimage/package-appimage.sh
          mv dist/Flowkeeper-*.AppImage "$PREFIX.AppImage"

          echo "Zipping the standalone directory"
          cd dist/standalone
          zip -9 -r "../../$PREFIX-standalone.zip" ./*
          cd ../..

          echo "Cleaning /dist up"
          rm -rf dist/standalone

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          name: "Build ${{ inputs.tag }}"
          prerelease: true
          files: "dist/*"